import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/TopMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShopDee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  showTopMenu = true,
}: Readonly<{
  children: React.ReactNode;
  showTopMenu?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {showTopMenu && <TopMenu/>}
        {children}
      </body>
    </html>
  );
}
